export const hebrew = {
  continue: 'המשך',
  fullName: 'שם מלא',
  email: 'מייל',
  message: 'הודעה',
  wellcome: 'ברוכים הבאים!',
  return_welcome: 'כיף שחזרת',
  return_subTitle: 'הזינו מספר טלפון כדי שנשלח לך\n קוד התחברות :)',
  forConnection: 'כדי להכיר טוב נשמח שתכתוב/י את שמך ומספר הטלפון',
  smsText: 'קיבלתם סמס, הזינו את הקוד שמופיע בו לא קיבלתם? ',
  great: 'מעולה!',
  finish: 'סיום',
  pushHere: 'לחצו כאן',
  hi: 'היי ',
  to_archive: 'ארכיון בקשות',
  archive: 'ארכיון',
  to_reviews: 'חוות דעת',
  location: 'מיקום',
  cofirmTerms: 'קראתי את',
  confirmAge: 'אני מעל גיל 18',
  terms: 'תנאי השימוש',
  privacy_policy: 'מדיניות פרטיות',
  markPicture: 'כדי למחוק תמונה מההודעה, סמן את התמונה ולחץ על כפתור המחיקה',
  aboutUsBody: `זיגיט היא הבית של קבוצה של אנשי טכנולוגיה נלהבים שאוהבים להוביל פעילויות מובייל ואינטרנט.

  מהשלב הראשוני וחווית משתמש ועיצוב, דרך פיתוח Full Stack ועד לניהול שוטף.
  
  מאז שנוסדנו ב-2010, צברנו ניסיון עשיר בעבודה עם ארגונים מובילים וארגונים בינלאומיים ממגזרים שונים, ומספקים להם פלטפורמות דיגיטליות מתקדמות.`,
  dummy_text:
    'לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית לורם איפסום דולור סיט אמט.',
  niceToKnow: 'נעים להכיר :)',
  optionToHelp: 'הגעת אלינו כדי לעזור לאחרים או כדי לקבל עזרה?',
  takeMeHomePage: 'קחו אותי לעמוד הבית!',
  edit_pic: 'עדכן תמונה',
  // helpOther: "עזרה לאחרים",
  insert_id: 'על מנת שנוכל להמשיך בבטחה, אנא צלם תעודה מזהה ',
  add_image: 'הוסף.י תמונה',
  replace_image: 'החלפת תמונה',
  helpOther: 'לכל הבקשות',
  gettingHelp: 'קבלת עזרה',
  whatIsYourIntrest: 'מהם תחומי העניין שלך?',
  choosingIntrest: 'כדי להתאים לך את הבקשות אפשר לבחור מתחומי העניין הבאים:',
  thankSForCorperation: 'תודה על השיתוף פעולה',
  importentForYouToKnow:
    'חשוב לנו שתדע! \n  אנחנו מתחייבים לא להפנות מצידינו אלייך \n שום בקשות לעזרה.',
  importentForYouToKnow2:
    'נתינת עזרה, הינה פעולה אקטיבית שרק \n במידה ואתה בוחר לעזור אנחנו נדאג לתהליך \n קל ונח לטובת שני הצדדים.',
  thanksForHelping: '!תודה שבחרת לעזור',
  cameraAsking:
    ' על מנת שנוכל להמשיך בבטחה, אנא צלם \n סלפי של עצמך עם תעודה מזהה' +
    '\n\n' +
    'לאחר שתוסיף את התמונה, היא תהיה תמונת הפרופיל שלך. \n אל דאגה, זוהי פעולה חד פעמית :)',
  cameraAsking2:
    'לאחר שתוסיף את התמונה, היא תהיה תמונת הפרופיל שלך. אל דרגה, זוהי פעולה חד פעמית :)',
  open_camera: 'פתח מצלמה',
  safe_use: 'שימוש בטוח',
  safe_use_body: `על מנת שנוכל להמשיך בבטחה,
  אנא צלם את התעודה מזהה
 
 לאחר שתוסיף את התמונה, היא תהיה בשימוש פנימי ולא תוצג למשתמשים
 
 אל דאגה, זוהי פעולה חד פעמית :)`,
  open_galery: 'פתח גלרייה',
  selesfiedFromPics: 'האם ברצונך להמשיך עם בחירתך?',
  picFromGallery: 'תמונות מגלריה',
  yes: 'כן',
  no: 'לא',
  pic_choose_overload: 'בחרת תמונות מעל המותר נא נסה שנית!',
  your_Selfi_Pic: 'תמונת הסלפי שלך!',
  img_recived: 'התמונה התקבלה',
  img_cleard: 'אנא וודאו שהתמונה ברורה',
  fixising: 'תיקונים',
  yesterday: 'אתמול',
  meterFromYourPlace: 'מטר ממך',
  Km_from_you: 'קמ ממך',
  readMore: 'קרא עוד',
  showLess: 'תראה פחות',
  offerHelp: 'הצע עזרה',
  share: 'שתפו בקשה',
  // help_to_others: "עזרה לאחרים",
  help_to_others: 'לכל הבקשות',
  missions_under_my_hand: 'התנדבויות שלי',
  please_try_again: 'קוד שגוי בבקשה לנסות שוב!',
  sms_code: 'קוד סמס',
  skip: 'דלג',
  main: 'ראשי',
  waiting_to_gettingHelpPerson: 'ממתין לאישור',
  active: 'פעיל',
  cancel_post: 'לא אוכל לעזור, בטל',
  cancel_Your_Offer: 'בטל את הצעתך',
  contact: 'צור קשר',
  start_call: 'התחל שיחה',
  enterProfile: 'צפה בפרופיל',
  offerHisHelp: 'הציע את עזרתו לבקשה:',
  to_help_with: 'לבקשת העזרה',
  confirmContact: 'אנא צור קשר כדי לתאם את ההתנדבות',
  confirmRevelDetails: 'אנא אשר את חשיפת פרטי ההתקשרות',
  get_to_know: 'על מנת להכיר ולתאם צור בבקשה קשר עם המתנדב',
  approve_requst: 'בקשות שאושרו',
  pandding_requst: 'בקשות ממתינות',
  deleting: 'מחיקה',
  delete: 'מחק',
  close: 'סגור',
  back_to_homePage: 'חזור לעמוד הבית',
  say_thanks: 'להגיד תודה',
  edit: 'עריכה',
  approve_requst_byGettingHelpSide: 'אשר.י קבלת העזרה',
  adding_new_requst: 'הוספת בקשה חדשה',
  edit_requst: 'עדכון בקשה קיימת',
  choosen_Category: 'בחר.י קטגוריה',
  title_of_request: 'כותרת הבקשה',
  body_of_request: 'תוכן הבקשה',
  body_of_request_review: 'כתוב כמה מילים על תוכן החוויה',
  add_picture: 'הוסף.י תמונה',
  publish_request: 'פרסם בקשה',
  publish: 'פרסם',
  publish__edit_request: 'עדכן שינוי',
  profile_details: 'פרטי הפרופיל',
  request_details: 'פרטי בקשה',
  missing_Fileds: 'שדות חסרים אנא הקפד לממלא את כל השדות',
  post_sending_succsed: 'פוסט הועלה בהצלחה!',
  today: 'היום',
  day_before_yesterday: 'שלשום',
  days: 'ימים',
  before: 'מלפני',
  problem_solved: 'תקלה נפתרה',
  manual_location_ask:
    'בשביל שתוכל להנות מהאפילקציה בצורה מיטבית אנא הכנס את המיקום בצורה ידנית',
  manual_location: 'הכנסת מיקום',
  entering_address: 'חפש מיקום',
  defineLocation: 'הגדר מיקום',
  enterLocation: 'הכנס אזור כדי שהמשתמשים יוכלו לדעת איפה אתה נמצא',
  moving_Status_ask: 'האם אתה בטוח שברצונך לעבור מצב?',
  changing_user_status: 'שינוי סטטוס',
  alertOf_ChangingStatus1:
    'כרגע הינך נותן עזרה, אם ברצונך גם לקבל עזרה אנא הכנס להגדרות פרופיל ותשנה זאת גם למצב מקבל עזרה. ',
  alertOf_ChangingStatus2:
    'כרגע הינך מקבל עזרה, אם ברצונך גם לעזור לאחרים אנא הכנס להגדרות פרופיל ותשנה זאת גם למצב נותן עזרה. ',
  require_Settings_change: 'דרוש שינוי בהגדרות',
  ok: 'בסדר',
  settings: 'הגדרות',
  general: 'כללי',
  privacy: 'פרטיות',
  deleteAccount: 'מחיקת חשבון',
  deleteAccountTitle: 'מחיקת החשבון תעלים את כל המידע שנצבר באפליקציה',
  notification: 'התראות',
  receive_notification: 'קבלת התראות לטלפון',
  location_permission: 'אשר שימוש במיקום מכשירך',
  homePage: 'עמוד הבית',
  profile: 'פרופיל',
  reviews: 'חוות דעת',
  my_profile: 'הפרופיל שלי',
  edit_profile: 'עריכת פרופיל',
  littleBit_aboutUs: 'קצת עלינו',
  contect_Us: 'יצירת קשר',
  contect_Us_title: 'אל תהססו לדבר איתנו',
  disconnect: 'התנתק',
  we_set: 'קבענו!',
  israel: 'ישראל',
  phone_exists_tryagain: 'מספר הטלפון כבר קיים במערכת נסה מספר אחר',
  phone_exists_inSystem: 'טלפון קיים במערכת',
  phone_changed: 'החלפת את מספר הטלפון',
  phone_change_appRestart: 'מספר הטלפון הוחלף, האפליקציה תתאתחל',
  upgrade_givingAndGetting: 'שדרג לקבלת ונתינת עזרה',
  save_changes: 'שמור',
  update_categories: 'עדכן תחומי עניין:',
  update_phone: 'טלפון',
  tell_us: 'כמה מילים על עצמך',
  update_profile: 'שם',
  no_reviews: 'עדיין אין חוות דעת',
  no_reviews_body: 'בקרוב יהיו פה שיתופים על החוויות משותפות',
  no_application_approved: 'אין כאן עדיין בקשות פעילות',
  no_application_approved_body:
    'לא קיימות בקשות פעילות אתם יכולים לנסות שוב מחר ואולי יהיו חדשות ',
  no_newRequsrt_givingHelp:
    ' לא קיימות בקשות פעילות אתם יכולים ליצור בקשה חדשה ולקבל עזרה בהצלחה!',
  no_available_request: 'אתם יכולים לנסות שוב מחר ואולי יהיו בקשות חדשות',
  no_request_UnderMyHand: 'לא קיימות משימות',
  no_request_UnderMyHand_body:
    ' לא קיימות משימות תבחרו מהרשימה ותתחילו להנות לעזור לאנשים בהצלחה!',
  cancelB: 'בטל',
  read_feedback: 'קרא משוב',
  write_feedback: 'כתוב משוב',
  send: 'שלח',
  my_requests: 'בקשות שלי',
  request_underMYHand: 'בקשות בטיפולי',
  requets_everyone: 'בקשות של כולם',
  requets_everyone_underhand: 'בקשות בטיפול כל השאר',
  post_ByCategory: 'פוסטים לפי קטגוריה',
  MyPost_Vs_EveryOne: 'הפוסטים שלי מול כולם',
  statistics: 'סטיסטיקות',
  rate: 'ממוצע הדירוג שלך',
  Login_Input_Error: 'בבקשה מלא שם ומספר טלפון בעל 10 ספרות!',
  phoneWithstar: 'טלפון*',
  phone: 'טלפון',
  name_with_starr: '*שם',
  fullName_with_starr:'שם מלא*',
  name: 'שם',
  choose_atLeast_one_option: 'בבקשה תבחר לפחות אופציה אחת!',
  map: 'מפה',
  do_you_want_navigationPoat: 'האם ברצונך לנווט לפוסט שלחצת?',
  move_to_post: 'פרטי פוסט',
  set_time: 'קבענו!',
  do_you_want_to_deletePost: 'האם ברצונך למחוק את טיוטת הפוסט שיצרת?',
  filter_by_distance: 'מיין לפי מרחק',
  filter_by_date: 'מיין לפי תאריך',
  all: 'הכל',
  feedBack_forThankYou: 'משוב הכרת תודה :)',
  do_you_wantmanuakNaviagtion:
    'האם ברצונך להמשיך או להזין כתובת אחרת ממה שהזנת ?',
  manual_navigation: 'מיקום ידני',
  DoYouWant_selfi_gallery: 'האם ברצונך לקחת תמונת סלפי או להשתמש בגלריה',
  chenge_pic: 'שינוי תמונה',
  camera_permission: 'הרשאות מצלמה',
  dont_have_camera_permmision:
    'אין לאפליקציה הרשאה להשתמש במצלמה, האם תרצה לתת כזאת ?',
  are_you_sure: 'בטוחים?',
  success_publish: 'הבקשה פורסמה בהצלחה!',
  success_confirm: 'הבקשה אושרה',
  info_as_sent: 'פרטי ההתקשרות נשלחו',
  welcomeToContact: ' אתה מוזמן ליצור קשר לתיאום',
  success_send: 'הבקשה נשלחה בהצלחה!',
  thanks_got_contacting: 'תודה שפנית,נחזור אליך בהקדם',
  success_publish_subTitle: `הבקשה שלך פורסמה לכלל המתנדבים,
  עקוב אחרי סטטוס הבקשה 
  `,
  are_you_sure_Delete: 'את בטוח שתרצה למחוק את הבקשה?',
  are_you_sure_fullText: 'אתה בטוח שאתה רוצה לצאת מהמשתמש שלך באפליקציה?',
  see_you_next_time: 'נתראה בפעם\n הבאה (:',
  we_wanted_to_say_thanks: 'רצינו להגיד תודה',
  we_wanted_to_say_thanks_fulltext:
    'על עשייה משמעותית, הזמן שהוקדש והבחירה להיות חלק.',
  confirm: 'אישור',
  confirming: 'מאשר',
  approve: 'אשר',
  phone_wrong_alert: 'שים לב שהמספרים נכונים,קורה שמתבלבלים :)',
  did_you_get_code: 'קיבלת קוד?',
  you_got_code_now: 'ברגעים אלה נשלח קוד לטלפון',
  enter_the_code: 'הכנס את הקוד',
  didnt_get: 'לא קיבלתם?',
  put_code: 'הזינו את הקוד',
  currentLocation: 'מיקומך הנוכחי',
  oneOf_details_wrong: 'אחד או יותר מהפריטים שהוזנו שגוי',
  termsNotFiled: 'אשר את תנאי השימוש האפליקציה',
  fun_toBePart_of: 'כיף להיות חלק מקהילה שבאה לעשות קצת יותר טוב בעולם,',
  choose_activity: 'בחר מה עיקר הפעילות שלך:',
  your_privecy_is_importent:
    'הפרטיות שלך חשובה לנו,\n הקמנו את האפליקציה כדי לייצר חיבור\n קל ונוח לשני הצדדים,',
  connection_made_after_approval: 'חיבור יקרה רק במידה ותאשר',
  we_commit_not_to_show:
    'אנחנו מחוייבים לא להציג את פרטייך\n האישים ללא אישורך',
  start: 'התחל',
  we_commit_not_to_approach:
    'אנחנו מתחייבים לא להפנות אלייך שום בקשות לעזרה ללא אישורך',
  my_post: 'בקשה חדשה',
  wait_for_answer: 'ממתין לתשובה',
  request_in_process: 'בקשה בתהליך',
  finish_request: 'הסתיים',
  cancel_request: 'ביטול בקשה',
  all_requests: 'כל הבקשות',
  my_requsts: 'הבקשות שלי',
  cancel_your_request: 'בטל את הצעתך',
  make_contect: 'צור קשר',
  not_this_time: 'לא הפעם',
  the_profile_of: 'הפרופיל של',
  close_request: 'סגור בקשה',
  are_you_sure_close_request: 'אתה בטוח שתרצה לסגור את הבקשה',
  leave_open: 'השאר פתוחה',
  request_closed_successfully: 'הבקשה נסגרה בהצלחה!',
  we_will_happy_to_hear_your_opinion: 'נשמח לשמוע על חווית התנדבות',
  pulish_recommendation: 'פרסם חוות דעת',
  add_recommmendtion: 'הוסף חוות דעת',
  rate_your_openion_on_valenter: 'דרג את מידת שביעות הרצון שלך מהמתנדב',
  five_starts_max: '5 כוכבים מרוצה מאוד',
  publish_successfully: 'פורסם בהצלחה!',
  thanks_sharing_your_recommendtion:
    'תודה ששיתפת, \nחוות הדעת שלך תפורסם בעבמוד הפרופיל\n של המתנדב',
  no_application_in_archive: 'אין כאן עדיין בקשות בארכיון',
  you_can_try_tommarrow: 'אתם יכולים לנסות שוב מחר ואולי יהו חדשות',
  add_recommendation: 'הוסף המלצה',
  recommendation_dont_exist: 'לא קיימות חוות דעת על המשתמש',
  profile_of: 'הפרופיל של',
  push_watch_details: 'לחץ לצפייה בפרטים',
  tooManyImages: 'שים לב - צריך למחוק את אחת התמונות כדי להוסיף תמונה חדשה',
  newVolunteer: 'איזה כיף! \nיש מתנדב',
  newVolunteering: 'איזה כיף! \n ההתנדבות אושרה',
  not_working_out: 'הפעם לא הסתדר',
  request_returning:
    'הבקשה חזרה להיות פתוחה לכלל\n המתנדבים, מקווים שתמצא התאמה',
  cancel_volunteer:
    'בחר לבטל את ההתנדבות שנקבעה, הבקשה תחזור להיות פתוחה לכלל המשתתפים',
  cancel_gettingHelp: 'בחר לבטל את הצעתך, תודה על הנכונות לעזור',
};
